from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

def generate_report(name, company, email):

    file_path = "financial_report.pdf"

    c = canvas.Canvas(file_path, pagesize=letter)

    c.setFont("Helvetica", 14)

    c.drawString(50,750,"FinPilot AI Financial Report")

    c.drawString(50,700,f"Name: {name}")
    c.drawString(50,680,f"Company: {company}")
    c.drawString(50,660,f"Email: {email}")

    c.drawString(50,620,"Financial Insights Generated by FinPilot AI")

    c.save()

    return file_path
